export const d: {
  id: number;
  move_id: number;
  name_ko: string;
  name_en: string;
  name_ja: string;
  type: string;
  power: number | null;
  accuracy: number | null;
  damage_class: string;
  pp: number | null;
  move_number: number;
  identifier: string;
  description: string;
}[] = [
  {
    id: 1,
    move_id: 1,
    name_ko: '막치기',
    name_en: 'Pound',
    name_ja: 'はたく',
    type: 'normal',
    power: 40,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 1,
    identifier: 'pound',
    description: '긴 꼬리나 손 등을 사용하여 상대를 때려서 공격한다.',
  },
  {
    id: 2,
    move_id: 2,
    name_ko: '태권당수',
    name_en: 'Karate Chop',
    name_ja: 'からてチョップ',
    type: 'normal',
    power: 50,
    accuracy: 100,
    damage_class: 'physical',
    pp: 25,
    move_number: 2,
    identifier: 'karate-chop',
    description: '날카로운 당수로 상대를 때려서 공격한다. 급소에 맞기 쉽다.',
  },
  {
    id: 3,
    move_id: 3,
    name_ko: '연속뺨치기',
    name_en: 'Double Slap',
    name_ja: 'おうふくビンタ',
    type: 'normal',
    power: 15,
    accuracy: 85,
    damage_class: 'physical',
    pp: 10,
    move_number: 3,
    identifier: 'double-slap',
    description:
      '연속 뺨치기로 상대를 때려서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 4,
    move_id: 4,
    name_ko: '연속펀치',
    name_en: 'Comet Punch',
    name_ja: 'れんぞくパンチ',
    type: 'normal',
    power: 18,
    accuracy: 85,
    damage_class: 'physical',
    pp: 15,
    move_number: 4,
    identifier: 'comet-punch',
    description:
      '노도 같은 펀치로 상대를 세게 때려서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 5,
    move_id: 5,
    name_ko: '메가톤펀치',
    name_en: 'Mega Punch',
    name_ja: 'メガトンパンチ',
    type: 'normal',
    power: 80,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 5,
    identifier: 'mega-punch',
    description: '힘을 담은 펀치로 상대를 공격한다.',
  },
  {
    id: 6,
    move_id: 6,
    name_ko: '고양이돈받기',
    name_en: 'Pay Day',
    name_ja: 'ネコにこばん',
    type: 'normal',
    power: 40,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 6,
    identifier: 'pay-day',
    description:
      '상대의 몸에 돈을 세게 던져서 공격한다. 배틀 후에 돈을 받을 수 있다.',
  },
  {
    id: 7,
    move_id: 7,
    name_ko: '불꽃펀치',
    name_en: 'Fire Punch',
    name_ja: 'ほのおのパンチ',
    type: 'fire',
    power: 75,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 7,
    identifier: 'fire-punch',
    description:
      '불꽃을 담은 펀치로 상대를 공격한다. 화상 상태로 만들 때가 있다.',
  },
  {
    id: 8,
    move_id: 8,
    name_ko: '냉동펀치',
    name_en: 'Ice Punch',
    name_ja: 'れいとうパンチ',
    type: 'ice',
    power: 75,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 8,
    identifier: 'ice-punch',
    description:
      '냉기를 담은 펀치로 상대를 공격한다. 얼음 상태로 만들 때가 있다.',
  },
  {
    id: 9,
    move_id: 9,
    name_ko: '번개펀치',
    name_en: 'Thunder Punch',
    name_ja: 'かみなりパンチ',
    type: 'electric',
    power: 75,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 9,
    identifier: 'thunder-punch',
    description:
      '전격을 담은 펀치로 상대를 공격한다. 마비 상태로 만들 때가 있다.',
  },
  {
    id: 10,
    move_id: 10,
    name_ko: '할퀴기',
    name_en: 'Scratch',
    name_ja: 'ひっかく',
    type: 'normal',
    power: 40,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 10,
    identifier: 'scratch',
    description: '단단하고 뾰족한 날카로운 손톱으로 상대를 할퀴어서 공격한다.',
  },
  {
    id: 11,
    move_id: 11,
    name_ko: '찝기',
    name_en: 'Vise Grip',
    name_ja: 'はさむ',
    type: 'normal',
    power: 55,
    accuracy: 100,
    damage_class: 'physical',
    pp: 30,
    move_number: 11,
    identifier: 'vise-grip',
    description: '상대를 양쪽에서 집어서 데미지를 준다.',
  },
  {
    id: 12,
    move_id: 12,
    name_ko: '가위자르기',
    name_en: 'Guillotine',
    name_ja: 'ハサミギロチン',
    type: 'normal',
    power: null,
    accuracy: 30,
    damage_class: 'physical',
    pp: 5,
    move_number: 12,
    identifier: 'guillotine',
    description: '큰 집게로 상대를 베어 갈라 공격한다. 맞으면 일격에 기절한다.',
  },
  {
    id: 13,
    move_id: 13,
    name_ko: '칼바람',
    name_en: 'Razor Wind',
    name_ja: 'かまいたち',
    type: 'normal',
    power: 80,
    accuracy: 75,
    damage_class: 'physical',
    pp: 10,
    move_number: 13,
    identifier: 'razor-wind',
    description:
      '바람의 칼날을 만들어 2턴째에 상대를 공격한다. 급소에 맞기 쉽다.',
  },
  {
    id: 14,
    move_id: 14,
    name_ko: '칼춤',
    name_en: 'Swords Dance',
    name_ja: 'つるぎのまい',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 14,
    identifier: 'swords-dance',
    description:
      '싸움의 춤을 격렬하게 추며 기세를 높인다. 자신의 공격을 크게 올린다.',
  },
  {
    id: 15,
    move_id: 15,
    name_ko: '풀베기',
    name_en: 'Cut',
    name_ja: 'いあいぎり',
    type: 'normal',
    power: 50,
    accuracy: 95,
    damage_class: 'physical',
    pp: 30,
    move_number: 15,
    identifier: 'cut',
    description:
      '낫이나 발톱 등으로 상대를 베어 공격한다. 가느다란 나무도 자를 수 있다.',
  },
  {
    id: 16,
    move_id: 16,
    name_ko: '바람일으키기',
    name_en: 'Gust',
    name_ja: 'かぜおこし',
    type: 'normal',
    power: 40,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 16,
    identifier: 'gust',
    description: '날개로 일으킨 격한 바람을 상대에게 부딪쳐서 공격한다.',
  },
  {
    id: 17,
    move_id: 17,
    name_ko: '날개치기',
    name_en: 'Wing Attack',
    name_ja: 'つばさでうつ',
    type: 'flying',
    power: 35,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 17,
    identifier: 'wing-attack',
    description: '크게 펼친 훌륭한 날개를 상대에게 부딪쳐서 공격한다.',
  },
  {
    id: 18,
    move_id: 18,
    name_ko: '날려버리기',
    name_en: 'Whirlwind',
    name_ja: 'ふきとばし',
    type: 'normal',
    power: null,
    accuracy: 85,
    damage_class: 'status',
    pp: 20,
    move_number: 18,
    identifier: 'whirlwind',
    description:
      '상대를 날려버려서 교대할 포켓몬을 끌어낸다. 야생의 경우에는 배틀이 끝난다.',
  },
  {
    id: 19,
    move_id: 19,
    name_ko: '공중날기',
    name_en: 'Fly',
    name_ja: 'そらをとぶ',
    type: 'flying',
    power: 70,
    accuracy: 95,
    damage_class: 'physical',
    pp: 15,
    move_number: 19,
    identifier: 'fly',
    description:
      '1턴째에 하늘을 날아 2턴째에 상대를 공격한다. 알고 있는 도시로 날아갈 수 있다.',
  },
  {
    id: 20,
    move_id: 20,
    name_ko: '조이기',
    name_en: 'Bind',
    name_ja: 'しめつける',
    type: 'normal',
    power: 15,
    accuracy: 75,
    damage_class: 'physical',
    pp: 20,
    move_number: 20,
    identifier: 'bind',
    description: '긴 몸이나 덩굴 등을 써서 4-5턴 동안 상대를 조여 공격한다.',
  },
  {
    id: 21,
    move_id: 21,
    name_ko: '힘껏치기',
    name_en: 'Slam',
    name_ja: 'たたきつける',
    type: 'normal',
    power: 80,
    accuracy: 75,
    damage_class: 'physical',
    pp: 20,
    move_number: 21,
    identifier: 'slam',
    description: '긴 꼬리나 덩굴 등을 사용해 상대를 힘껏 쳐서 공격한다.',
  },
  {
    id: 22,
    move_id: 22,
    name_ko: '덩굴채찍',
    name_en: 'Vine Whip',
    name_ja: 'つるのムチ',
    type: 'grass',
    power: 35,
    accuracy: 100,
    damage_class: 'special',
    pp: 10,
    move_number: 22,
    identifier: 'vine-whip',
    description:
      '채찍처럼 휘어지는 가늘고 긴 덩굴로 상대를 힘껏 쳐서 공격한다.',
  },
  {
    id: 23,
    move_id: 23,
    name_ko: '짓밟기',
    name_en: 'Stomp',
    name_ja: 'ふみつけ',
    type: 'normal',
    power: 65,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 23,
    identifier: 'stomp',
    description:
      '큰 발로 상대를 짓밟아서 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 24,
    move_id: 24,
    name_ko: '두번치기',
    name_en: 'Double Kick',
    name_ja: 'にどげり',
    type: 'fighting',
    power: 30,
    accuracy: 100,
    damage_class: 'physical',
    pp: 30,
    move_number: 24,
    identifier: 'double-kick',
    description:
      '2개의 다리로 상대를 걷어차서 공격한다. 2회 연속으로 데미지를 준다.',
  },
  {
    id: 25,
    move_id: 25,
    name_ko: '메가톤킥',
    name_en: 'Mega Kick',
    name_ja: 'メガトンキック',
    type: 'normal',
    power: 120,
    accuracy: 75,
    damage_class: 'physical',
    pp: 5,
    move_number: 25,
    identifier: 'mega-kick',
    description: '굉장한 힘을 담은 킥으로 상대를 걷어차서 공격한다.',
  },
  {
    id: 26,
    move_id: 26,
    name_ko: '점프킥',
    name_en: 'Jump Kick',
    name_ja: 'とびげり',
    type: 'fighting',
    power: 70,
    accuracy: 95,
    damage_class: 'physical',
    pp: 25,
    move_number: 26,
    identifier: 'jump-kick',
    description:
      '높이 점프해서 킥으로 상대를 공격한다. 빗나가면 자신이 데미지를 입는다.',
  },
  {
    id: 27,
    move_id: 27,
    name_ko: '돌려차기',
    name_en: 'Rolling Kick',
    name_ja: 'まわしげり',
    type: 'fighting',
    power: 60,
    accuracy: 85,
    damage_class: 'physical',
    pp: 15,
    move_number: 27,
    identifier: 'rolling-kick',
    description:
      '몸을 재빨리 회전시키며 걷어차서 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 28,
    move_id: 28,
    name_ko: '모래뿌리기',
    name_en: 'Sand Attack',
    name_ja: 'すなかけ',
    type: 'normal',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 15,
    move_number: 28,
    identifier: 'sand-attack',
    description: '상대의 얼굴에 모래를 뿌려서 명중률을 떨어뜨린다.',
  },
  {
    id: 29,
    move_id: 29,
    name_ko: '박치기',
    name_en: 'Headbutt',
    name_ja: 'ずつき',
    type: 'normal',
    power: 70,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 29,
    identifier: 'headbutt',
    description:
      '머리를 내밀어 곧장 돌진하여 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 30,
    move_id: 30,
    name_ko: '뿔찌르기',
    name_en: 'Horn Attack',
    name_ja: 'つのでつく',
    type: 'normal',
    power: 65,
    accuracy: 100,
    damage_class: 'physical',
    pp: 25,
    move_number: 30,
    identifier: 'horn-attack',
    description: '날카롭고 뾰족한 뿔로 상대를 공격한다.',
  },
  {
    id: 31,
    move_id: 31,
    name_ko: '마구찌르기',
    name_en: 'Fury Attack',
    name_ja: 'みだれづき',
    type: 'normal',
    power: 15,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 31,
    identifier: 'fury-attack',
    description:
      '뿔이나 부리로 상대를 찔러서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 32,
    move_id: 32,
    name_ko: '뿔드릴',
    name_en: 'Horn Drill',
    name_ja: 'つのドリル',
    type: 'normal',
    power: null,
    accuracy: 30,
    damage_class: 'physical',
    pp: 5,
    move_number: 32,
    identifier: 'horn-drill',
    description:
      '회전하는 뿔을 상대에게 꿰찔러서 공격한다. 맞으면 일격에 기절한다.',
  },
  {
    id: 33,
    move_id: 33,
    name_ko: '몸통박치기',
    name_en: 'Tackle',
    name_ja: 'たいあたり',
    type: 'normal',
    power: 35,
    accuracy: 95,
    damage_class: 'physical',
    pp: 35,
    move_number: 33,
    identifier: 'tackle',
    description: '상대를 향해서 몸 전체를 부딪쳐가며 공격한다.',
  },
  {
    id: 34,
    move_id: 34,
    name_ko: '누르기',
    name_en: 'Body Slam',
    name_ja: 'のしかかり',
    type: 'normal',
    power: 85,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 34,
    identifier: 'body-slam',
    description:
      '몸 전체로 상대를 덮쳐 눌러 공격한다. 마비 상태로 만들 때가 있다.',
  },
  {
    id: 35,
    move_id: 35,
    name_ko: '김밥말이',
    name_en: 'Wrap',
    name_ja: 'まきつく',
    type: 'normal',
    power: 15,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 35,
    identifier: 'wrap',
    description:
      '긴 몸이나 덩굴 등을 사용해 4-5턴 동안 상대를 휘감아 공격한다.',
  },
  {
    id: 36,
    move_id: 36,
    name_ko: '돌진',
    name_en: 'Take Down',
    name_ja: 'とっしん',
    type: 'normal',
    power: 90,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 36,
    identifier: 'take-down',
    description:
      '굉장한 기세로 상대에게 부딪쳐 공격한다. 자신도 조금 데미지를 입는다.',
  },
  {
    id: 37,
    move_id: 37,
    name_ko: '난동부리기',
    name_en: 'Thrash',
    name_ja: 'あばれる',
    type: 'normal',
    power: 90,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 37,
    identifier: 'thrash',
    description:
      '2-3턴 동안 마구 난동 부려서 상대를 공격한다. 난동 부린 뒤에는 혼란에 빠진다.',
  },
  {
    id: 38,
    move_id: 38,
    name_ko: '이판사판태클',
    name_en: 'Double-Edge',
    name_ja: 'すてみタックル',
    type: 'normal',
    power: 100,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 38,
    identifier: 'double-edge',
    description:
      '목숨을 걸고 상대에게 돌진하여 공격을 한다. 자신도 상당한 데미지를 입는다.',
  },
  {
    id: 39,
    move_id: 39,
    name_ko: '꼬리흔들기',
    name_en: 'Tail Whip',
    name_ja: 'しっぽをふる',
    type: 'normal',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 30,
    move_number: 39,
    identifier: 'tail-whip',
    description:
      '꼬리를 좌우로 귀엽게 흔들어 방심을 유도한다. 상대의 방어를 떨어뜨린다.',
  },
  {
    id: 40,
    move_id: 40,
    name_ko: '독침',
    name_en: 'Poison Sting',
    name_ja: 'どくばり',
    type: 'poison',
    power: 15,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 40,
    identifier: 'poison-sting',
    description:
      '독이 있는 침을 상대에게 꿰찔러서 공격한다. 독 상태로 만들 때가 있다.',
  },
  {
    id: 41,
    move_id: 41,
    name_ko: '더블니들',
    name_en: 'Twineedle',
    name_ja: 'ダブルニードル',
    type: 'bug',
    power: 25,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 41,
    identifier: 'twineedle',
    description:
      '2개의 침을 상대에게 꿰찔러 2회 연속으로 데미지를 준다. 독 상태로 만들 때가 있다.',
  },
  {
    id: 42,
    move_id: 42,
    name_ko: '바늘미사일',
    name_en: 'Pin Missile',
    name_ja: 'ミサイルばり',
    type: 'bug',
    power: 14,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 42,
    identifier: 'pin-missile',
    description:
      '날카로운 침을 상대에게 발사해서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 43,
    move_id: 43,
    name_ko: '째려보기',
    name_en: 'Leer',
    name_ja: 'にらみつける',
    type: 'normal',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 30,
    move_number: 43,
    identifier: 'leer',
    description: '날카로운 눈초리로 겁을 주어 상대의 방어를 떨어뜨린다.',
  },
  {
    id: 44,
    move_id: 44,
    name_ko: '물기',
    name_en: 'Bite',
    name_ja: 'かみつく',
    type: 'normal',
    power: 60,
    accuracy: 100,
    damage_class: 'physical',
    pp: 25,
    move_number: 44,
    identifier: 'bite',
    description:
      '날카롭고 뾰족한 이빨로 물어서 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 45,
    move_id: 45,
    name_ko: '울음소리',
    name_en: 'Growl',
    name_ja: 'なきごえ',
    type: 'normal',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 40,
    move_number: 45,
    identifier: 'growl',
    description:
      '귀여운 울음소리를 들려주고 관심을 끌어 방심한 사이에 상대의 공격을 떨어뜨린다.',
  },
  {
    id: 46,
    move_id: 46,
    name_ko: '울부짖기',
    name_en: 'Roar',
    name_ja: 'ほえる',
    type: 'normal',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 20,
    move_number: 46,
    identifier: 'roar',
    description:
      '상대를 도망가게 해서 교대할 포켓몬을 끌어낸다. 야생의 경우에는 배틀이 끝난다.',
  },
  {
    id: 47,
    move_id: 47,
    name_ko: '노래하기',
    name_en: 'Sing',
    name_ja: 'うたう',
    type: 'normal',
    power: null,
    accuracy: 55,
    damage_class: 'status',
    pp: 15,
    move_number: 47,
    identifier: 'sing',
    description:
      '기분 좋은 예쁜 노랫소리를 들려주고 상대를 잠듦 상태로 만든다.',
  },
  {
    id: 48,
    move_id: 48,
    name_ko: '초음파',
    name_en: 'Supersonic',
    name_ja: 'ちょうおんぱ',
    type: 'normal',
    power: null,
    accuracy: 55,
    damage_class: 'status',
    pp: 20,
    move_number: 48,
    identifier: 'supersonic',
    description: '특수한 음파를 몸에서 발산하여 상대를 혼란시킨다.',
  },
  {
    id: 49,
    move_id: 49,
    name_ko: '소닉붐',
    name_en: 'Sonic Boom',
    name_ja: 'ソニックブーム',
    type: 'normal',
    power: null,
    accuracy: 90,
    damage_class: 'physical',
    pp: 20,
    move_number: 49,
    identifier: 'sonic-boom',
    description:
      '충격파를 상대에 부딪쳐서 공격한다. 언제나 20의 데미지를 준다.',
  },
  {
    id: 50,
    move_id: 50,
    name_ko: '사슬묶기',
    name_en: 'Disable',
    name_ja: 'かなしばり',
    type: 'normal',
    power: null,
    accuracy: 55,
    damage_class: 'status',
    pp: 20,
    move_number: 50,
    identifier: 'disable',
    description:
      '상대의 움직임을 막아 바로 전에 쓴 기술을 4턴 동안 사용할 수 없게 만든다.',
  },
  {
    id: 51,
    move_id: 51,
    name_ko: '용해액',
    name_en: 'Acid',
    name_ja: 'ようかいえき',
    type: 'poison',
    power: 40,
    accuracy: 100,
    damage_class: 'physical',
    pp: 30,
    move_number: 51,
    identifier: 'acid',
    description:
      '강한 산을 상대에게 끼얹어 공격한다. 상대의 특수방어를 떨어뜨릴 때가 있다.',
  },
  {
    id: 52,
    move_id: 52,
    name_ko: '불꽃세례',
    name_en: 'Ember',
    name_ja: 'ひのこ',
    type: 'fire',
    power: 40,
    accuracy: 100,
    damage_class: 'special',
    pp: 25,
    move_number: 52,
    identifier: 'ember',
    description:
      '작은 불꽃을 상대에게 발사하여 공격한다. 화상 상태로 만들 때가 있다.',
  },
  {
    id: 53,
    move_id: 53,
    name_ko: '화염방사',
    name_en: 'Flamethrower',
    name_ja: 'かえんほうしゃ',
    type: 'fire',
    power: 95,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 53,
    identifier: 'flamethrower',
    description:
      '세찬 불꽃을 상대에게 발사하여 공격한다. 화상 상태로 만들 때가 있다.',
  },
  {
    id: 54,
    move_id: 54,
    name_ko: '흰안개',
    name_en: 'Mist',
    name_ja: 'しろいきり',
    type: 'ice',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 54,
    identifier: 'mist',
    description:
      '하얀 안개로 몸을 덮는다. 5턴 동안 상대에 의해 능력이 떨어지지 않게 된다.',
  },
  {
    id: 55,
    move_id: 55,
    name_ko: '물대포',
    name_en: 'Water Gun',
    name_ja: 'みずでっぽう',
    type: 'water',
    power: 40,
    accuracy: 100,
    damage_class: 'special',
    pp: 25,
    move_number: 55,
    identifier: 'water-gun',
    description: '물을 기세 좋게 상대에게 발사하여 공격한다.',
  },
  {
    id: 56,
    move_id: 56,
    name_ko: '하이드로펌프',
    name_en: 'Hydro Pump',
    name_ja: 'ハイドロポンプ',
    type: 'water',
    power: 120,
    accuracy: 80,
    damage_class: 'special',
    pp: 5,
    move_number: 56,
    identifier: 'hydro-pump',
    description: '대량의 물을 세찬 기세로 상대에게 발사하여 공격한다.',
  },
  {
    id: 57,
    move_id: 57,
    name_ko: '파도타기',
    name_en: 'Surf',
    name_ja: 'なみのり',
    type: 'water',
    power: 95,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 57,
    identifier: 'surf',
    description:
      '큰 파도로 자신의 주위에 있는 포켓몬을 공격한다. 물 위도 헤엄쳐서 나아간다.',
  },
  {
    id: 58,
    move_id: 58,
    name_ko: '냉동빔',
    name_en: 'Ice Beam',
    name_ja: 'れいとうビーム',
    type: 'ice',
    power: 95,
    accuracy: 100,
    damage_class: 'special',
    pp: 10,
    move_number: 58,
    identifier: 'ice-beam',
    description:
      '냉동빔을 상대에게 발사하여 공격한다. 얼음 상태로 만들 때가 있다.',
  },
  {
    id: 59,
    move_id: 59,
    name_ko: '눈보라',
    name_en: 'Blizzard',
    name_ja: 'ふぶき',
    type: 'ice',
    power: 120,
    accuracy: 90,
    damage_class: 'special',
    pp: 5,
    move_number: 59,
    identifier: 'blizzard',
    description:
      '세찬 눈보라를 상대에게 내뿜어 공격한다. 얼음 상태로 만들 때가 있다.',
  },
  {
    id: 60,
    move_id: 60,
    name_ko: '환상빔',
    name_en: 'Psybeam',
    name_ja: 'サイケこうせん',
    type: 'psychic',
    power: 65,
    accuracy: 100,
    damage_class: 'special',
    pp: 20,
    move_number: 60,
    identifier: 'psybeam',
    description:
      '이상한 광선을 상대에게 발사하여 공격한다. 혼란시킬 때가 있다.',
  },
  {
    id: 61,
    move_id: 61,
    name_ko: '거품광선',
    name_en: 'Bubble Beam',
    name_ja: 'バブルこうせん',
    type: 'water',
    power: 65,
    accuracy: 100,
    damage_class: 'special',
    pp: 20,
    move_number: 61,
    identifier: 'bubble-beam',
    description:
      '거품을 기세 좋게 상대에게 발사하여 공격한다. 스피드를 떨어뜨릴 때가 있다.',
  },
  {
    id: 62,
    move_id: 62,
    name_ko: '오로라빔',
    name_en: 'Aurora Beam',
    name_ja: 'オーロラビーム',
    type: 'ice',
    power: 65,
    accuracy: 100,
    damage_class: 'special',
    pp: 20,
    move_number: 62,
    identifier: 'aurora-beam',
    description:
      '무지개색의 빔을 상대에게 발사하여 공격한다. 공격을 떨어뜨릴 때가 있다.',
  },
  {
    id: 63,
    move_id: 63,
    name_ko: '파괴광선',
    name_en: 'Hyper Beam',
    name_ja: 'はかいこうせん',
    type: 'normal',
    power: 150,
    accuracy: 90,
    damage_class: 'physical',
    pp: 5,
    move_number: 63,
    identifier: 'hyper-beam',
    description:
      '강한 광선을 상대에게 발사하여 공격한다. 다음 턴은 움직일 수 없다.',
  },
  {
    id: 64,
    move_id: 64,
    name_ko: '쪼기',
    name_en: 'Peck',
    name_ja: 'つつく',
    type: 'flying',
    power: 35,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 64,
    identifier: 'peck',
    description: '날카롭고 뾰족한 부리나 뿔로 상대를 쪼아서 공격한다.',
  },
  {
    id: 65,
    move_id: 65,
    name_ko: '회전부리',
    name_en: 'Drill Peck',
    name_ja: 'ドリルくちばし',
    type: 'flying',
    power: 80,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 65,
    identifier: 'drill-peck',
    description: '회전하면서 뾰족한 부리를 상대에게 꿰찔러 공격한다.',
  },
  {
    id: 66,
    move_id: 66,
    name_ko: '지옥의바퀴',
    name_en: 'Submission',
    name_ja: 'じごくぐるま',
    type: 'fighting',
    power: 80,
    accuracy: 80,
    damage_class: 'physical',
    pp: 25,
    move_number: 66,
    identifier: 'submission',
    description:
      '땅에 자신과 함께 상대를 내던져 공격한다. 자신도 조금 데미지를 입는다.',
  },
  {
    id: 67,
    move_id: 67,
    name_ko: '안다리걸기',
    name_en: 'Low Kick',
    name_ja: 'けたぐり',
    type: 'fighting',
    power: 50,
    accuracy: 90,
    damage_class: 'physical',
    pp: 20,
    move_number: 67,
    identifier: 'low-kick',
    description:
      '발을 강하게 걸고 상대를 넘어뜨려 공격한다. 상대가 무거울수록 위력이 올라간다.',
  },
  {
    id: 68,
    move_id: 68,
    name_ko: '카운터',
    name_en: 'Counter',
    name_ja: 'カウンター',
    type: 'fighting',
    power: null,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 68,
    identifier: 'counter',
    description:
      '상대로부터 받은 물리공격의 데미지를 2배로 만들어 같은 상대에게 돌려준다.',
  },
  {
    id: 69,
    move_id: 69,
    name_ko: '지구던지기',
    name_en: 'Seismic Toss',
    name_ja: 'ちきゅうなげ',
    type: 'fighting',
    power: null,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 69,
    identifier: 'seismic-toss',
    description:
      '인력을 사용해 내던진다. 자신의 레벨과 똑같은 데미지를 상대에게 준다.',
  },
  {
    id: 70,
    move_id: 70,
    name_ko: '괴력',
    name_en: 'Strength',
    name_ja: 'かいりき',
    type: 'normal',
    power: 80,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 70,
    identifier: 'strength',
    description:
      '혼신의 힘으로 상대를 세게 때려서 공격한다. 무거운 돌을 밀 수도 있다.',
  },
  {
    id: 71,
    move_id: 71,
    name_ko: '흡수',
    name_en: 'Absorb',
    name_ja: 'すいとる',
    type: 'grass',
    power: 20,
    accuracy: 100,
    damage_class: 'special',
    pp: 20,
    move_number: 71,
    identifier: 'absorb',
    description:
      '양분을 흡수하여 공격한다. 상대에게 입힌 데미지의 절반에 해당하는 HP를 회복할 수 있다.',
  },
  {
    id: 72,
    move_id: 72,
    name_ko: '메가드레인',
    name_en: 'Mega Drain',
    name_ja: 'メガドレイン',
    type: 'grass',
    power: 40,
    accuracy: 100,
    damage_class: 'special',
    pp: 10,
    move_number: 72,
    identifier: 'mega-drain',
    description:
      '양분을 흡수하여 공격한다. 상대에게 입힌 데미지의 절반에 해당하는 HP를 회복할 수 있다.',
  },
  {
    id: 73,
    move_id: 73,
    name_ko: '씨뿌리기',
    name_en: 'Leech Seed',
    name_ja: 'やどりぎのタネ',
    type: 'grass',
    power: null,
    accuracy: 90,
    damage_class: 'status',
    pp: 10,
    move_number: 73,
    identifier: 'leech-seed',
    description:
      '씨가 뿌려진 상대의 HP를 매 턴 조금씩 흡수하여 자신의 HP를 회복한다.',
  },
  {
    id: 74,
    move_id: 74,
    name_ko: '성장',
    name_en: 'Growth',
    name_ja: 'せいちょう',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 40,
    move_number: 74,
    identifier: 'growth',
    description: '몸을 일시에 크게 성장시켜 공격과 특수공격을 올린다.',
  },
  {
    id: 75,
    move_id: 75,
    name_ko: '잎날가르기',
    name_en: 'Razor Leaf',
    name_ja: 'はっぱカッター',
    type: 'grass',
    power: 55,
    accuracy: 95,
    damage_class: 'special',
    pp: 25,
    move_number: 75,
    identifier: 'razor-leaf',
    description: '잎사귀를 날려 상대를 베어 공격한다. 급소에 맞기 쉽다.',
  },
  {
    id: 76,
    move_id: 76,
    name_ko: '솔라빔',
    name_en: 'Solar Beam',
    name_ja: 'ソーラービーム',
    type: 'grass',
    power: 120,
    accuracy: 100,
    damage_class: 'special',
    pp: 10,
    move_number: 76,
    identifier: 'solar-beam',
    description:
      '1턴째에 빛을 가득 모아 2턴째에 빛의 다발을 발사하여 공격한다.',
  },
  {
    id: 77,
    move_id: 77,
    name_ko: '독가루',
    name_en: 'Poison Powder',
    name_ja: 'どくのこな',
    type: 'poison',
    power: null,
    accuracy: 75,
    damage_class: 'status',
    pp: 35,
    move_number: 77,
    identifier: 'poison-powder',
    description: '독이 있는 가루를 많이 흩뿌려서 상대를 독 상태로 만든다.',
  },
  {
    id: 78,
    move_id: 78,
    name_ko: '저리가루',
    name_en: 'Stun Spore',
    name_ja: 'しびれごな',
    type: 'grass',
    power: null,
    accuracy: 75,
    damage_class: 'status',
    pp: 30,
    move_number: 78,
    identifier: 'stun-spore',
    description: '저리 가루를 많이 흩뿌려서 상대를 마비 상태로 만든다.',
  },
  {
    id: 79,
    move_id: 79,
    name_ko: '수면가루',
    name_en: 'Sleep Powder',
    name_ja: 'ねむりごな',
    type: 'grass',
    power: null,
    accuracy: 75,
    damage_class: 'status',
    pp: 15,
    move_number: 79,
    identifier: 'sleep-powder',
    description: '잠이 오는 가루를 많이 흩뿌려서 상대를 잠듦 상태로 만든다.',
  },
  {
    id: 80,
    move_id: 80,
    name_ko: '꽃잎댄스',
    name_en: 'Petal Dance',
    name_ja: 'はなびらのまい',
    type: 'grass',
    power: 70,
    accuracy: 100,
    damage_class: 'special',
    pp: 20,
    move_number: 80,
    identifier: 'petal-dance',
    description:
      '2-3턴 동안 꽃을 흩뿌려서 상대를 공격한다. 흩뿌린 뒤에는 혼란에 빠진다.',
  },
  {
    id: 81,
    move_id: 81,
    name_ko: '실뿜기',
    name_en: 'String Shot',
    name_ja: 'いとをはく',
    type: 'bug',
    power: null,
    accuracy: 95,
    damage_class: 'status',
    pp: 40,
    move_number: 81,
    identifier: 'string-shot',
    description: '입에서 뿜어낸 실을 휘감아서 상대의 스피드를 크게 떨어뜨린다.',
  },
  {
    id: 82,
    move_id: 82,
    name_ko: '용의분노',
    name_en: 'Dragon Rage',
    name_ja: 'りゅうのいかり',
    type: 'dragon',
    power: null,
    accuracy: 100,
    damage_class: 'special',
    pp: 10,
    move_number: 82,
    identifier: 'dragon-rage',
    description:
      '분노의 충격파를 상대에게 부딪쳐서 공격한다. 언제나 40의 데미지를 준다.',
  },
  {
    id: 83,
    move_id: 83,
    name_ko: '회오리불꽃',
    name_en: 'Fire Spin',
    name_ja: 'ほのおのうず',
    type: 'fire',
    power: 15,
    accuracy: 70,
    damage_class: 'special',
    pp: 15,
    move_number: 83,
    identifier: 'fire-spin',
    description:
      '세차게 소용돌이치는 불꽃 속에 4-5턴 동안 상대를 가두어 공격한다.',
  },
  {
    id: 84,
    move_id: 84,
    name_ko: '전기쇼크',
    name_en: 'Thunder Shock',
    name_ja: 'でんきショック',
    type: 'electric',
    power: 40,
    accuracy: 100,
    damage_class: 'special',
    pp: 30,
    move_number: 84,
    identifier: 'thunder-shock',
    description:
      '전기 자극을 상대에게 날려서 공격한다. 마비 상태로 만들 때가 있다.',
  },
  {
    id: 85,
    move_id: 85,
    name_ko: '10만볼트',
    name_en: 'Thunderbolt',
    name_ja: '１０まんボルト',
    type: 'electric',
    power: 95,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 85,
    identifier: 'thunderbolt',
    description:
      '강한 전격을 상대에게 날려서 공격한다. 마비 상태로 만들 때가 있다.',
  },
  {
    id: 86,
    move_id: 86,
    name_ko: '전기자석파',
    name_en: 'Thunder Wave',
    name_ja: 'でんじは',
    type: 'electric',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 20,
    move_number: 86,
    identifier: 'thunder-wave',
    description: '약한 전격을 날려서 상대를 마비 상태로 만든다.',
  },
  {
    id: 87,
    move_id: 87,
    name_ko: '번개',
    name_en: 'Thunder',
    name_ja: 'かみなり',
    type: 'electric',
    power: 120,
    accuracy: 70,
    damage_class: 'special',
    pp: 10,
    move_number: 87,
    identifier: 'thunder',
    description:
      '강한 번개를 상대에게 떨어뜨려 공격한다. 마비 상태로 만들 때가 있다.',
  },
  {
    id: 88,
    move_id: 88,
    name_ko: '돌떨구기',
    name_en: 'Rock Throw',
    name_ja: 'いわおとし',
    type: 'rock',
    power: 50,
    accuracy: 65,
    damage_class: 'physical',
    pp: 15,
    move_number: 88,
    identifier: 'rock-throw',
    description: '작은 바위를 들어올려 상대에게 내던져서 공격한다.',
  },
  {
    id: 89,
    move_id: 89,
    name_ko: '지진',
    name_en: 'Earthquake',
    name_ja: 'じしん',
    type: 'ground',
    power: 100,
    accuracy: 100,
    damage_class: 'physical',
    pp: 10,
    move_number: 89,
    identifier: 'earthquake',
    description: '지진의 충격으로 자신의 주위에 있는 포켓몬을 공격한다.',
  },
  {
    id: 90,
    move_id: 90,
    name_ko: '땅가르기',
    name_en: 'Fissure',
    name_ja: 'じわれ',
    type: 'ground',
    power: null,
    accuracy: 30,
    damage_class: 'physical',
    pp: 5,
    move_number: 90,
    identifier: 'fissure',
    description:
      '땅이 갈라진 곳에 상대를 떨어뜨려 공격한다. 맞으면 일격에 기절한다.',
  },
  {
    id: 91,
    move_id: 91,
    name_ko: '구멍파기',
    name_en: 'Dig',
    name_ja: 'あなをほる',
    type: 'ground',
    power: 100,
    accuracy: 100,
    damage_class: 'physical',
    pp: 10,
    move_number: 91,
    identifier: 'dig',
    description:
      '1턴째에 파고들어 2턴째에 상대를 공격한다. 동굴에서 탈출할 수도 있다.',
  },
  {
    id: 92,
    move_id: 92,
    name_ko: '맹독',
    name_en: 'Toxic',
    name_ja: 'どくどく',
    type: 'poison',
    power: null,
    accuracy: 85,
    damage_class: 'status',
    pp: 10,
    move_number: 92,
    identifier: 'toxic',
    description:
      '상대를 맹독의 상태로 만든다. 턴이 진행될수록 독의 데미지가 증가한다.',
  },
  {
    id: 93,
    move_id: 93,
    name_ko: '염동력',
    name_en: 'Confusion',
    name_ja: 'ねんりき',
    type: 'psychic',
    power: 50,
    accuracy: 100,
    damage_class: 'special',
    pp: 25,
    move_number: 93,
    identifier: 'confusion',
    description:
      '약한 염동력을 상대에게 보내어 공격한다. 상대를 혼란시킬 때가 있다.',
  },
  {
    id: 94,
    move_id: 94,
    name_ko: '사이코키네시스',
    name_en: 'Psychic',
    name_ja: 'サイコキネシス',
    type: 'psychic',
    power: 90,
    accuracy: 100,
    damage_class: 'special',
    pp: 10,
    move_number: 94,
    identifier: 'psychic',
    description:
      '강한 염동력을 상대에게 보내어 공격한다. 상대의 특수방어를 떨어뜨릴 때가 있다.',
  },
  {
    id: 95,
    move_id: 95,
    name_ko: '최면술',
    name_en: 'Hypnosis',
    name_ja: 'さいみんじゅつ',
    type: 'psychic',
    power: null,
    accuracy: 60,
    damage_class: 'status',
    pp: 20,
    move_number: 95,
    identifier: 'hypnosis',
    description: '졸음을 유도하는 암시를 걸어서 상대를 잠듦 상태로 만든다.',
  },
  {
    id: 96,
    move_id: 96,
    name_ko: '요가포즈',
    name_en: 'Meditate',
    name_ja: 'ヨガのポーズ',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 40,
    move_number: 96,
    identifier: 'meditate',
    description: '잠들어 있는 힘을 몸속에서 끌어내어 자신의 공격을 올린다.',
  },
  {
    id: 97,
    move_id: 97,
    name_ko: '고속이동',
    name_en: 'Agility',
    name_ja: 'こうそくいどう',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 97,
    identifier: 'agility',
    description:
      '힘을 빼고 몸을 가볍게 해서 고속으로 움직인다. 자신의 스피드를 크게 올린다.',
  },
  {
    id: 98,
    move_id: 98,
    name_ko: '전광석화',
    name_en: 'Quick Attack',
    name_ja: 'でんこうせっか',
    type: 'normal',
    power: 40,
    accuracy: 100,
    damage_class: 'physical',
    pp: 30,
    move_number: 98,
    identifier: 'quick-attack',
    description:
      '눈에 보이지 않는 굉장한 속도로 상대에게 돌진한다. 반드시 선제공격할 수 있다.',
  },
  {
    id: 99,
    move_id: 99,
    name_ko: '분노',
    name_en: 'Rage',
    name_ja: 'いかり',
    type: 'normal',
    power: 20,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 99,
    identifier: 'rage',
    description: '기술을 썼을 때 공격을 받으면 분노의 힘으로 공격이 올라간다.',
  },
  {
    id: 100,
    move_id: 100,
    name_ko: '순간이동',
    name_en: 'Teleport',
    name_ja: 'テレポート',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 20,
    move_number: 100,
    identifier: 'teleport',
    description:
      '야생 포켓몬과 배틀을 그만둔다. 마지막에 들어갔던 포켓몬센터가 있는 도시에도 갈 수 있다.',
  },
  {
    id: 101,
    move_id: 101,
    name_ko: '나이트헤드',
    name_en: 'Night Shade',
    name_ja: 'ナイトヘッド',
    type: 'ghost',
    power: null,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 101,
    identifier: 'night-shade',
    description:
      '무시무시한 환상을 보게 해서 자신의 레벨과 똑같은 만큼의 데미지를 상대에게 준다.',
  },
  {
    id: 102,
    move_id: 102,
    name_ko: '흉내내기',
    name_en: 'Mimic',
    name_ja: 'ものまね',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 10,
    move_number: 102,
    identifier: 'mimic',
    description:
      '상대가 마지막에 사용한 기술을 배틀을 하는 동안 자신의 기술로 만들 수 있다.',
  },
  {
    id: 103,
    move_id: 103,
    name_ko: '싫은소리',
    name_en: 'Screech',
    name_ja: 'いやなおと',
    type: 'normal',
    power: null,
    accuracy: 85,
    damage_class: 'status',
    pp: 40,
    move_number: 103,
    identifier: 'screech',
    description:
      '그만 귀를 막아버리고 싶은 싫은 소리를 내어 상대의 방어를 크게 떨어뜨린다.',
  },
  {
    id: 104,
    move_id: 104,
    name_ko: '그림자분신',
    name_en: 'Double Team',
    name_ja: 'かげぶんしん',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 15,
    move_number: 104,
    identifier: 'double-team',
    description:
      '재빠른 움직임으로 분신을 만들어 상대를 혼란시켜 회피율을 올린다.',
  },
  {
    id: 105,
    move_id: 105,
    name_ko: 'HP회복',
    name_en: 'Recover',
    name_ja: 'じこさいせい',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 20,
    move_number: 105,
    identifier: 'recover',
    description: '세포를 재생시켜 자신의 최대 HP의 절반만큼 HP를 회복한다.',
  },
  {
    id: 106,
    move_id: 106,
    name_ko: '단단해지기',
    name_en: 'Harden',
    name_ja: 'かたくなる',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 106,
    identifier: 'harden',
    description: '전신에 힘을 담아 몸을 단단하게 해서 자신의 방어를 올린다.',
  },
  {
    id: 107,
    move_id: 107,
    name_ko: '작아지기',
    name_en: 'Minimize',
    name_ja: 'ちいさくなる',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 20,
    move_number: 107,
    identifier: 'minimize',
    description: '몸을 축소하여 작게 보임으로써 자신의 회피율을 크게 올린다.',
  },
  {
    id: 108,
    move_id: 108,
    name_ko: '연막',
    name_en: 'Smokescreen',
    name_ja: 'えんまく',
    type: 'normal',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 20,
    move_number: 108,
    identifier: 'smokescreen',
    description: '연기나 먹물을 내뿜어 상대의 명중률을 떨어뜨린다.',
  },
  {
    id: 109,
    move_id: 109,
    name_ko: '이상한빛',
    name_en: 'Confuse Ray',
    name_ja: 'あやしいひかり',
    type: 'ghost',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 10,
    move_number: 109,
    identifier: 'confuse-ray',
    description: '이상한 빛을 상대에게 비춰 당황하게 한다. 상대를 혼란시킨다.',
  },
  {
    id: 110,
    move_id: 110,
    name_ko: '껍질에숨기',
    name_en: 'Withdraw',
    name_ja: 'からにこもる',
    type: 'water',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 40,
    move_number: 110,
    identifier: 'withdraw',
    description: '껍질에 숨어 몸을 보호하여 자신의 방어를 올린다.',
  },
  {
    id: 111,
    move_id: 111,
    name_ko: '웅크리기',
    name_en: 'Defense Curl',
    name_ja: 'まるくなる',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 40,
    move_number: 111,
    identifier: 'defense-curl',
    description: '몸을 둥글게 웅크려서 자신의 방어를 올린다.',
  },
  {
    id: 112,
    move_id: 112,
    name_ko: '배리어',
    name_en: 'Barrier',
    name_ja: 'バリアー',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 112,
    identifier: 'barrier',
    description: '튼튼한 장막을 만들어 자신의 방어를 크게 올린다.',
  },
  {
    id: 113,
    move_id: 113,
    name_ko: '빛의장막',
    name_en: 'Light Screen',
    name_ja: 'ひかりのかべ',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 113,
    identifier: 'light-screen',
    description:
      '5턴 동안 이상한 장막으로 상대로부터 받는 특수공격의 데미지를 약하게 한다.',
  },
  {
    id: 114,
    move_id: 114,
    name_ko: '흑안개',
    name_en: 'Haze',
    name_ja: 'くろいきり',
    type: 'ice',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 114,
    identifier: 'haze',
    description:
      '흑안개를 뿜어 배틀에 참가 중인 포켓몬 전원의 능력 변화를 원래대로 돌린다.',
  },
  {
    id: 115,
    move_id: 115,
    name_ko: '리플렉터',
    name_en: 'Reflect',
    name_ja: 'リフレクター',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 20,
    move_number: 115,
    identifier: 'reflect',
    description:
      '5턴 동안 이상한 장막으로 상대로부터 받는 물리공격의 데미지를 약하게 한다.',
  },
  {
    id: 116,
    move_id: 116,
    name_ko: '기충전',
    name_en: 'Focus Energy',
    name_ja: 'きあいだめ',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 116,
    identifier: 'focus-energy',
    description:
      '깊게 숨을 들이마셔 기합을 넣는다. 자신의 공격이 급소에 맞기 쉬워진다.',
  },
  {
    id: 117,
    move_id: 117,
    name_ko: '참기',
    name_en: 'Bide',
    name_ja: 'がまん',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'physical',
    pp: 10,
    move_number: 117,
    identifier: 'bide',
    description:
      '2턴 동안 공격을 견뎌 입은 데미지를 2배로 만들어 상대에게 돌려준다.',
  },
  {
    id: 118,
    move_id: 118,
    name_ko: '손가락흔들기',
    name_en: 'Metronome',
    name_ja: 'ゆびをふる',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 10,
    move_number: 118,
    identifier: 'metronome',
    description:
      '손가락을 흔들어 자신의 뇌를 자극해서 모든 기술 중 어느 하나를 날린다.',
  },
  {
    id: 119,
    move_id: 119,
    name_ko: '따라하기',
    name_en: 'Mirror Move',
    name_ja: 'オウムがえし',
    type: 'flying',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 20,
    move_number: 119,
    identifier: 'mirror-move',
    description: '상대가 사용한 기술을 흉내 내어 자신도 똑같은 기술을 쓴다.',
  },
  {
    id: 120,
    move_id: 120,
    name_ko: '자폭',
    name_en: 'Self-Destruct',
    name_ja: 'じばく',
    type: 'normal',
    power: 130,
    accuracy: 100,
    damage_class: 'physical',
    pp: 5,
    move_number: 120,
    identifier: 'self-destruct',
    description:
      '폭발을 일으켜서 자신의 주위에 있는 포켓몬을 공격한다. 쓰고 나서 기절하게 된다.',
  },
  {
    id: 121,
    move_id: 121,
    name_ko: '알폭탄',
    name_en: 'Egg Bomb',
    name_ja: 'タマゴばくだん',
    type: 'normal',
    power: 100,
    accuracy: 75,
    damage_class: 'physical',
    pp: 10,
    move_number: 121,
    identifier: 'egg-bomb',
    description: '큰 알을 온 힘을 다해 상대에게 내던져서 공격한다.',
  },
  {
    id: 122,
    move_id: 122,
    name_ko: '핥기',
    name_en: 'Lick',
    name_ja: 'したでなめる',
    type: 'ghost',
    power: 20,
    accuracy: 100,
    damage_class: 'physical',
    pp: 30,
    move_number: 122,
    identifier: 'lick',
    description: '긴 혀로 상대를 핥아서 공격한다. 마비 상태로 만들 때가 있다.',
  },
  {
    id: 123,
    move_id: 123,
    name_ko: '스모그',
    name_en: 'Smog',
    name_ja: 'スモッグ',
    type: 'poison',
    power: 20,
    accuracy: 70,
    damage_class: 'physical',
    pp: 20,
    move_number: 123,
    identifier: 'smog',
    description:
      '더러운 가스를 상대에게 내뿜어 공격한다. 독 상태로 만들 때가 있다.',
  },
  {
    id: 124,
    move_id: 124,
    name_ko: '오물공격',
    name_en: 'Sludge',
    name_ja: 'ヘドロこうげき',
    type: 'poison',
    power: 65,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 124,
    identifier: 'sludge',
    description:
      '더러운 오물을 상대에게 내던져서 공격한다. 독 상태로 만들 때가 있다.',
  },
  {
    id: 125,
    move_id: 125,
    name_ko: '뼈다귀치기',
    name_en: 'Bone Club',
    name_ja: 'ホネこんぼう',
    type: 'ground',
    power: 65,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 125,
    identifier: 'bone-club',
    description:
      '손에 들고 있는 뼈로 상대를 세게 때려서 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 126,
    move_id: 126,
    name_ko: '불대문자',
    name_en: 'Fire Blast',
    name_ja: 'だいもんじ',
    type: 'fire',
    power: 120,
    accuracy: 85,
    damage_class: 'special',
    pp: 5,
    move_number: 126,
    identifier: 'fire-blast',
    description:
      '큰 대자의 불꽃으로 상대를 불태운다. 화상 상태로 만들 때가 있다.',
  },
  {
    id: 127,
    move_id: 127,
    name_ko: '폭포오르기',
    name_en: 'Waterfall',
    name_ja: 'たきのぼり',
    type: 'water',
    power: 80,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 127,
    identifier: 'waterfall',
    description:
      '굉장한 기세로 상대에게 돌진한다. 상대를 풀죽게 만들 때가 있다. 폭포도 거슬러 올라갈 수 있다.',
  },
  {
    id: 128,
    move_id: 128,
    name_ko: '껍질끼우기',
    name_en: 'Clamp',
    name_ja: 'からではさむ',
    type: 'water',
    power: 35,
    accuracy: 75,
    damage_class: 'special',
    pp: 10,
    move_number: 128,
    identifier: 'clamp',
    description:
      '매우 튼튼하고 두꺼운 껍질에 4-5턴 동안 상대를 끼워서 공격한다.',
  },
  {
    id: 129,
    move_id: 129,
    name_ko: '스피드스타',
    name_en: 'Swift',
    name_ja: 'スピードスター',
    type: 'normal',
    power: 60,
    accuracy: null,
    damage_class: 'physical',
    pp: 20,
    move_number: 129,
    identifier: 'swift',
    description:
      '별 모양의 빛을 발사해서 상대를 공격한다. 공격은 반드시 명중한다.',
  },
  {
    id: 130,
    move_id: 130,
    name_ko: '로케트박치기',
    name_en: 'Skull Bash',
    name_ja: 'ロケットずつき',
    type: 'normal',
    power: 100,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 130,
    identifier: 'skull-bash',
    description:
      '1턴째에 머리를 움츠려 방어를 올린다. 2턴째에 상대를 공격한다.',
  },
  {
    id: 131,
    move_id: 131,
    name_ko: '가시대포',
    name_en: 'Spike Cannon',
    name_ja: 'とげキャノン',
    type: 'normal',
    power: 20,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 131,
    identifier: 'spike-cannon',
    description:
      '날카로운 침을 상대에게 발사해서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 132,
    move_id: 132,
    name_ko: '휘감기',
    name_en: 'Constrict',
    name_ja: 'からみつく',
    type: 'normal',
    power: 10,
    accuracy: 100,
    damage_class: 'physical',
    pp: 35,
    move_number: 132,
    identifier: 'constrict',
    description:
      '촉수나 덩굴 등을 휘감아서 공격한다. 상대의 스피드를 떨어뜨릴 때가 있다.',
  },
  {
    id: 133,
    move_id: 133,
    name_ko: '망각술',
    name_en: 'Amnesia',
    name_ja: 'ドわすれ',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 20,
    move_number: 133,
    identifier: 'amnesia',
    description:
      '머리를 비워서 순간적으로 무언가를 잊어버림으로써 자신의 특수방어를 크게 올린다.',
  },
  {
    id: 134,
    move_id: 134,
    name_ko: '숟가락휘기',
    name_en: 'Kinesis',
    name_ja: 'スプーンまげ',
    type: 'psychic',
    power: null,
    accuracy: 80,
    damage_class: 'status',
    pp: 15,
    move_number: 134,
    identifier: 'kinesis',
    description: '숟가락을 휘어서 주의를 끌어 상대의 명중률을 낮춘다.',
  },
  {
    id: 135,
    move_id: 135,
    name_ko: '알낳기',
    name_en: 'Soft-Boiled',
    name_ja: 'タマゴうみ',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 10,
    move_number: 135,
    identifier: 'soft-boiled',
    description:
      '자신의 최대 HP 절반을 회복한다. 동료에게 HP를 나누어 줄 수도 있다.',
  },
  {
    id: 136,
    move_id: 136,
    name_ko: '무릎차기',
    name_en: 'High Jump Kick',
    name_ja: 'とびひざげり',
    type: 'fighting',
    power: 85,
    accuracy: 90,
    damage_class: 'physical',
    pp: 20,
    move_number: 136,
    identifier: 'high-jump-kick',
    description:
      '점프해서 무릎차기로 상대를 공격한다. 빗나가면 자신이 데미지를 입는다.',
  },
  {
    id: 137,
    move_id: 137,
    name_ko: '뱀눈초리',
    name_en: 'Glare',
    name_ja: 'へびにらみ',
    type: 'normal',
    power: null,
    accuracy: 75,
    damage_class: 'status',
    pp: 30,
    move_number: 137,
    identifier: 'glare',
    description: '배의 무늬로 겁을 주어 상대를 마비 상태로 만든다.',
  },
  {
    id: 138,
    move_id: 138,
    name_ko: '꿈먹기',
    name_en: 'Dream Eater',
    name_ja: 'ゆめくい',
    type: 'psychic',
    power: 100,
    accuracy: 100,
    damage_class: 'special',
    pp: 15,
    move_number: 138,
    identifier: 'dream-eater',
    description:
      '잠자고 있는 상대의 꿈을 먹어 공격한다. 데미지의 절반을 HP로 회복한다.',
  },
  {
    id: 139,
    move_id: 139,
    name_ko: '독가스',
    name_en: 'Poison Gas',
    name_ja: 'どくガス',
    type: 'poison',
    power: null,
    accuracy: 55,
    damage_class: 'status',
    pp: 40,
    move_number: 139,
    identifier: 'poison-gas',
    description: '독가스를 상대의 얼굴에 내뿜어 독 상태로 만든다.',
  },
  {
    id: 140,
    move_id: 140,
    name_ko: '구슬던지기',
    name_en: 'Barrage',
    name_ja: 'たまなげ',
    type: 'normal',
    power: 15,
    accuracy: 85,
    damage_class: 'physical',
    pp: 20,
    move_number: 140,
    identifier: 'barrage',
    description:
      '둥근 것을 상대에게 내던져서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 141,
    move_id: 141,
    name_ko: '흡혈',
    name_en: 'Leech Life',
    name_ja: 'きゅうけつ',
    type: 'bug',
    power: 20,
    accuracy: 100,
    damage_class: 'physical',
    pp: 15,
    move_number: 141,
    identifier: 'leech-life',
    description:
      '피를 빨아서 상대를 공격한다. 준 데미지의 절반을 HP로 회복한다.',
  },
  {
    id: 142,
    move_id: 142,
    name_ko: '악마의키스',
    name_en: 'Lovely Kiss',
    name_ja: 'あくまのキッス',
    type: 'normal',
    power: null,
    accuracy: 75,
    damage_class: 'status',
    pp: 10,
    move_number: 142,
    identifier: 'lovely-kiss',
    description: '무서운 얼굴로 키스한다. 상대를 잠듦 상태로 만든다.',
  },
  {
    id: 143,
    move_id: 143,
    name_ko: '불새',
    name_en: 'Sky Attack',
    name_ja: 'ゴッドバード',
    type: 'flying',
    power: 140,
    accuracy: 90,
    damage_class: 'physical',
    pp: 5,
    move_number: 143,
    identifier: 'sky-attack',
    description:
      '2턴째에 상대를 공격한다. 가끔 풀죽게 만든다. 급소에도 맞기 쉽다.',
  },
  {
    id: 144,
    move_id: 144,
    name_ko: '변신',
    name_en: 'Transform',
    name_ja: 'へんしん',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 10,
    move_number: 144,
    identifier: 'transform',
    description:
      '상대 포켓몬으로 변신하여 상대와 완전히 똑같은 기술을 사용할 수 있다.',
  },
  {
    id: 145,
    move_id: 145,
    name_ko: '거품',
    name_en: 'Bubble',
    name_ja: 'あわ',
    type: 'water',
    power: 20,
    accuracy: 100,
    damage_class: 'special',
    pp: 30,
    move_number: 145,
    identifier: 'bubble',
    description:
      '매우 많은 거품을 상대에게 내뿜어 공격한다. 상대의 스피드를 떨어뜨릴 때가 있다.',
  },
  {
    id: 146,
    move_id: 146,
    name_ko: '잼잼펀치',
    name_en: 'Dizzy Punch',
    name_ja: 'ピヨピヨパンチ',
    type: 'normal',
    power: 70,
    accuracy: 100,
    damage_class: 'physical',
    pp: 10,
    move_number: 146,
    identifier: 'dizzy-punch',
    description: '리드미컬한 펀치를 날려 상대를 공격한다. 혼란시킬 때가 있다.',
  },
  {
    id: 147,
    move_id: 147,
    name_ko: '버섯포자',
    name_en: 'Spore',
    name_ja: 'キノコのほうし',
    type: 'grass',
    power: null,
    accuracy: 100,
    damage_class: 'status',
    pp: 15,
    move_number: 147,
    identifier: 'spore',
    description:
      '최면 효과가 있는 포자를 훌훌 흩뿌려서 상대를 잠듦 상태로 만든다.',
  },
  {
    id: 148,
    move_id: 148,
    name_ko: '플래시',
    name_en: 'Flash',
    name_ja: 'フラッシュ',
    type: 'normal',
    power: null,
    accuracy: 70,
    damage_class: 'status',
    pp: 20,
    move_number: 148,
    identifier: 'flash',
    description: '눈이 부신 빛으로 상대의 명중률을 떨어뜨린다.',
  },
  {
    id: 149,
    move_id: 149,
    name_ko: '사이코웨이브',
    name_en: 'Psywave',
    name_ja: 'サイコウェーブ',
    type: 'psychic',
    power: null,
    accuracy: 80,
    damage_class: 'special',
    pp: 15,
    move_number: 149,
    identifier: 'psywave',
    description:
      '이상한 염력파를 상대에게 발사하여 공격한다. 사용할 때마다 데미지가 바뀐다.',
  },
  {
    id: 150,
    move_id: 150,
    name_ko: '튀어오르기',
    name_en: 'Splash',
    name_ja: 'はねる',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 40,
    move_number: 150,
    identifier: 'splash',
    description: '공격도 하지 않고 팔딱팔딱 튈 뿐 아무 일도 일어나지 않는다...',
  },
  {
    id: 151,
    move_id: 151,
    name_ko: '녹기',
    name_en: 'Acid Armor',
    name_ja: 'とける',
    type: 'poison',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 40,
    move_number: 151,
    identifier: 'acid-armor',
    description: '세포의 변화로 액체가 되어 자신의 방어를 크게 올린다.',
  },
  {
    id: 152,
    move_id: 152,
    name_ko: '찝게햄머',
    name_en: 'Crabhammer',
    name_ja: 'クラブハンマー',
    type: 'water',
    power: 90,
    accuracy: 85,
    damage_class: 'special',
    pp: 10,
    move_number: 152,
    identifier: 'crabhammer',
    description: '큰 집게를 상대에게 내리쳐서 공격한다. 급소에 맞기 쉽다.',
  },
  {
    id: 153,
    move_id: 153,
    name_ko: '대폭발',
    name_en: 'Explosion',
    name_ja: 'だいばくはつ',
    type: 'normal',
    power: 170,
    accuracy: 100,
    damage_class: 'physical',
    pp: 5,
    move_number: 153,
    identifier: 'explosion',
    description:
      '큰 폭발로 자신의 주위에 있는 포켓몬을 공격한다. 쓰고 나서는 기절한다.',
  },
  {
    id: 154,
    move_id: 154,
    name_ko: '마구할퀴기',
    name_en: 'Fury Swipes',
    name_ja: 'みだれひっかき',
    type: 'normal',
    power: 18,
    accuracy: 80,
    damage_class: 'physical',
    pp: 15,
    move_number: 154,
    identifier: 'fury-swipes',
    description:
      '손톱이나 낫 등으로 상대를 할퀴어서 공격한다. 2-5회 동안 연속으로 쓴다.',
  },
  {
    id: 155,
    move_id: 155,
    name_ko: '뼈다귀부메랑',
    name_en: 'Bonemerang',
    name_ja: 'ホネブーメラン',
    type: 'ground',
    power: 50,
    accuracy: 90,
    damage_class: 'physical',
    pp: 10,
    move_number: 155,
    identifier: 'bonemerang',
    description:
      '손에 들고 있는 뼈를 상대에게 날려서 날아갈 때와 돌아올 때 2회 연속 데미지를 준다.',
  },
  {
    id: 156,
    move_id: 156,
    name_ko: '잠자기',
    name_en: 'Rest',
    name_ja: 'ねむる',
    type: 'psychic',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 10,
    move_number: 156,
    identifier: 'rest',
    description: '2턴 동안 계속 잠잔다. 자신의 HP와 상태 이상을 모두 회복한다.',
  },
  {
    id: 157,
    move_id: 157,
    name_ko: '스톤샤워',
    name_en: 'Rock Slide',
    name_ja: 'いわなだれ',
    type: 'rock',
    power: 75,
    accuracy: 90,
    damage_class: 'physical',
    pp: 10,
    move_number: 157,
    identifier: 'rock-slide',
    description:
      '큰 바위를 세차게 부딪쳐서 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 158,
    move_id: 158,
    name_ko: '필살앞니',
    name_en: 'Hyper Fang',
    name_ja: 'ひっさつまえば',
    type: 'normal',
    power: 80,
    accuracy: 90,
    damage_class: 'physical',
    pp: 15,
    move_number: 158,
    identifier: 'hyper-fang',
    description:
      '날카로운 앞니로 강하게 물어서 공격한다. 상대를 풀죽게 만들 때가 있다.',
  },
  {
    id: 159,
    move_id: 159,
    name_ko: '각지기',
    name_en: 'Sharpen',
    name_ja: 'かくばる',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 159,
    identifier: 'sharpen',
    description: '몸의 각을 늘려서 더욱 각지게 하여 자신의 공격을 올린다.',
  },
  {
    id: 160,
    move_id: 160,
    name_ko: '텍스처',
    name_en: 'Conversion',
    name_ja: 'テクスチャー',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 30,
    move_number: 160,
    identifier: 'conversion',
    description:
      '자신의 타입을 배운 기술 중 가장 위에 있는 기술과 같은 타입으로 바꾼다.',
  },
  {
    id: 161,
    move_id: 161,
    name_ko: '트라이어택',
    name_en: 'Tri Attack',
    name_ja: 'トライアタック',
    type: 'normal',
    power: 80,
    accuracy: 100,
    damage_class: 'physical',
    pp: 10,
    move_number: 161,
    identifier: 'tri-attack',
    description:
      '3개의 광선으로 공격한다. 마비, 화상 또는 얼음 상태 중 어느 하나로 만들 때가 있다.',
  },
  {
    id: 162,
    move_id: 162,
    name_ko: '분노의앞니',
    name_en: 'Super Fang',
    name_ja: 'いかりのまえば',
    type: 'normal',
    power: null,
    accuracy: 90,
    damage_class: 'physical',
    pp: 10,
    move_number: 162,
    identifier: 'super-fang',
    description:
      '날카로운 앞니로 강하게 물어서 공격한다. 상대의 HP는 절반이 된다.',
  },
  {
    id: 163,
    move_id: 163,
    name_ko: '베어가르기',
    name_en: 'Slash',
    name_ja: 'きりさく',
    type: 'normal',
    power: 70,
    accuracy: 100,
    damage_class: 'physical',
    pp: 20,
    move_number: 163,
    identifier: 'slash',
    description:
      '발톱이나 낫 등으로 상대를 베어 갈라서 공격한다. 급소에 맞기 쉽다.',
  },
  {
    id: 164,
    move_id: 164,
    name_ko: '대타출동',
    name_en: 'Substitute',
    name_ja: 'みがわり',
    type: 'normal',
    power: null,
    accuracy: null,
    damage_class: 'status',
    pp: 10,
    move_number: 164,
    identifier: 'substitute',
    description:
      '자신의 HP를 조금 깎아서 분신을 만든다. 분신은 자신의 대타가 된다.',
  },
  {
    id: 165,
    move_id: 165,
    name_ko: '발버둥',
    name_en: 'Struggle',
    name_ja: 'わるあがき',
    type: 'normal',
    power: 50,
    accuracy: null,
    damage_class: 'physical',
    pp: 10,
    move_number: 165,
    identifier: 'struggle',
    description:
      '자신의 PP가 떨어지면 발버둥 쳐 상대를 공격한다. 자신도 조금 데미지를 입는다.',
  },
];
