export const moves = [
  {
    level: 3,
    id: 8892,
    identifier: 'vine-whip',
    power: 45,
    accuracy: 100,
    pp: 25,
    type: 'grass',
    description:
      '채찍처럼 휘어지는 가늘고 긴 덩굴로 상대를 힘껏 쳐서 공격한다.',
    versionGroupId: 21,
    damageClass: 'physical',
    machineNumber: null,
    machineType: null,
    moveId: 22,
    moveNumber: 22,
    name: '덩굴채찍',
    nameEn: 'Vine Whip',
    nameJa: 'つるのムチ',
  },
  {
    level: 1,
    id: 8903,
    identifier: 'tackle',
    power: 40,
    accuracy: 100,
    pp: 35,
    type: 'normal',
    description: '상대를 향해서 몸 전체를 부딪쳐가며 공격한다.',
    versionGroupId: 21,
    damageClass: 'physical',
    machineNumber: null,
    machineType: null,
    moveId: 33,
    moveNumber: 33,
    name: '몸통박치기',
    nameEn: 'Tackle',
    nameJa: 'たいあたり',
  },
  {
    level: 21,
    id: 8906,
    identifier: 'take-down',
    power: 90,
    accuracy: 85,
    pp: 20,
    type: 'normal',
    description:
      '굉장한 기세로 상대에게 부딪쳐 공격한다. 자신도 조금 데미지를 입는다.',
    versionGroupId: 21,
    damageClass: 'physical',
    machineNumber: 1,
    machineType: 'TM',
    moveId: 36,
    moveNumber: 36,
    name: '돌진',
    nameEn: 'Take Down',
    nameJa: 'とっしん',
  },
  {
    level: 1,
    id: 8915,
    identifier: 'growl',
    power: null,
    accuracy: 100,
    pp: 40,
    type: 'normal',
    description:
      '귀여운 울음소리를 들려주고 관심을 끌어 방심한 사이에 상대의 공격을 떨어뜨린다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 45,
    moveNumber: 45,
    name: '울음소리',
    nameEn: 'Growl',
    nameJa: 'なきごえ',
  },
  {
    level: 9,
    id: 8943,
    identifier: 'leech-seed',
    power: null,
    accuracy: 90,
    pp: 10,
    type: 'grass',
    description:
      '씨가 뿌려진 상대의 HP를 매 턴 조금씩 흡수하여 자신의 HP를 회복한다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 73,
    moveNumber: 73,
    name: '씨뿌리기',
    nameEn: 'Leech Seed',
    nameJa: 'やどりぎのタネ',
  },
  {
    level: 6,
    id: 8944,
    identifier: 'growth',
    power: null,
    accuracy: null,
    pp: 20,
    type: 'normal',
    description: '몸을 일시에 크게 성장시켜 공격과 특수공격을 올린다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 74,
    moveNumber: 74,
    name: '성장',
    nameEn: 'Growth',
    nameJa: 'せいちょう',
  },
  {
    level: 12,
    id: 8945,
    identifier: 'razor-leaf',
    power: 55,
    accuracy: 95,
    pp: 25,
    type: 'grass',
    description: '잎사귀를 날려 상대를 베어 공격한다. 급소에 맞기 쉽다.',
    versionGroupId: 21,
    damageClass: 'physical',
    machineNumber: null,
    machineType: null,
    moveId: 75,
    moveNumber: 75,
    name: '잎날가르기',
    nameEn: 'Razor Leaf',
    nameJa: 'はっぱカッター',
  },
  {
    level: 36,
    id: 8946,
    identifier: 'solar-beam',
    power: 120,
    accuracy: 100,
    pp: 10,
    type: 'grass',
    description:
      '1턴째에 빛을 가득 모아 2턴째에 빛의 다발을 발사하여 공격한다.',
    versionGroupId: 21,
    damageClass: 'special',
    machineNumber: 168,
    machineType: 'TM',
    moveId: 76,
    moveNumber: 76,
    name: '솔라빔',
    nameEn: 'Solar Beam',
    nameJa: 'ソーラービーム',
  },
  {
    level: 15,
    id: 8947,
    identifier: 'poison-powder',
    power: null,
    accuracy: 75,
    pp: 35,
    type: 'poison',
    description: '독이 있는 가루를 많이 흩뿌려서 상대를 독 상태로 만든다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 77,
    moveNumber: 77,
    name: '독가루',
    nameEn: 'Poison Powder',
    nameJa: 'どくのこな',
  },
  {
    level: 15,
    id: 8949,
    identifier: 'sleep-powder',
    power: null,
    accuracy: 75,
    pp: 15,
    type: 'grass',
    description: '잠이 오는 가루를 많이 흩뿌려서 상대를 잠듦 상태로 만든다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 79,
    moveNumber: 79,
    name: '수면가루',
    nameEn: 'Sleep Powder',
    nameJa: 'ねむりごな',
  },
  {
    level: 24,
    id: 9100,
    identifier: 'sweet-scent',
    power: null,
    accuracy: 100,
    pp: 20,
    type: 'normal',
    description:
      '향기로 상대의 회피율을 크게 떨어뜨린다. 풀밭 등에서 쓰면 포켓몬이 다가온다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 230,
    moveNumber: 230,
    name: '달콤한향기',
    nameEn: 'Sweet Scent',
    nameJa: 'あまいかおり',
  },
  {
    level: 27,
    id: 9105,
    identifier: 'synthesis',
    power: null,
    accuracy: null,
    pp: 5,
    type: 'grass',
    description: '자신의 HP를 회복한다. 날씨에 따라 회복량이 변한다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 235,
    moveNumber: 235,
    name: '광합성',
    nameEn: 'Synthesis',
    nameJa: 'こうごうせい',
  },
  {
    level: 30,
    id: 9258,
    identifier: 'worry-seed',
    power: null,
    accuracy: 100,
    pp: 10,
    type: 'grass',
    description:
      '마음을 괴롭히는 씨앗을 심는다. 상대를 잠잘 수 없게 해서 특성을 불면으로 만든다.',
    versionGroupId: 21,
    damageClass: 'status',
    machineNumber: null,
    machineType: null,
    moveId: 388,
    moveNumber: 388,
    name: '고민씨',
    nameEn: 'Worry Seed',
    nameJa: 'なやみのタネ',
  },
  {
    level: 18,
    id: 9272,
    identifier: 'seed-bomb',
    power: 80,
    accuracy: 100,
    pp: 15,
    type: 'grass',
    description:
      '단단한 껍질을 가지고 있는 큰 씨앗을 힘껏 내던져 상대를 공격한다.',
    versionGroupId: 21,
    damageClass: 'physical',
    machineNumber: 71,
    machineType: 'TM',
    moveId: 402,
    moveNumber: 402,
    name: '씨폭탄',
    nameEn: 'Seed Bomb',
    nameJa: 'タネばくだん',
  },
  {
    level: 33,
    id: 9308,
    identifier: 'power-whip',
    power: 120,
    accuracy: 85,
    pp: 10,
    type: 'grass',
    description: '덩굴이나 촉수를 세차게 흔들어 상대를 힘껏 쳐서 공격한다.',
    versionGroupId: 21,
    damageClass: 'physical',
    machineNumber: null,
    machineType: null,
    moveId: 438,
    moveNumber: 438,
    name: '파워휩',
    nameEn: 'Power Whip',
    nameJa: 'パワーウィップ',
  },
];
